spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tabie_database
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#secret:
#  key: ${SECRET_KEY}